"""
Hermes Agent — interactive setup wizard.

Run: python setup_wizard.py
Walks you through every required configuration step and writes .env for you.
"""

import json
import os
import urllib.error
import urllib.request
from pathlib import Path

BASE = Path(__file__).parent
ENV_FILE = BASE / ".env"


def p(text: str = "") -> None:
    print(text)


def ask(prompt: str, default: str = "", secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    try:
        if secret:
            import getpass
            val = getpass.getpass(f"  {prompt}{suffix}: ").strip()
        else:
            val = input(f"  {prompt}{suffix}: ").strip()
    except (KeyboardInterrupt, EOFError):
        p("\nSetup cancelled.")
        raise SystemExit(0)
    return val or default


def ask_choice(prompt: str, choices: list[str], default: str) -> str:
    options = " / ".join(
        f"[{c}]" if c == default else c for c in choices
    )
    p(f"  {prompt}  ({options})")
    while True:
        val = ask("Your choice", default=default).lower()
        if val in choices:
            return val
        p(f"  Please enter one of: {', '.join(choices)}")


def test_telegram_token(token: str) -> str | None:
    """Returns bot username if valid, None if invalid."""
    try:
        url = f"https://api.telegram.org/bot{token}/getMe"
        with urllib.request.urlopen(url, timeout=10) as resp:
            data = json.loads(resp.read())
        return data["result"].get("username")
    except Exception:
        return None


def test_gemini_key(key: str) -> bool:
    try:
        import google.generativeai as genai
        genai.configure(api_key=key)
        model = genai.GenerativeModel("gemini-2.0-flash")
        model.generate_content("Say OK")
        return True
    except Exception:
        return False


def write_env(values: dict[str, str]) -> None:
    lines = ["# Hermes Agent — generated by setup_wizard.py", ""]
    for k, v in values.items():
        if v:
            lines.append(f"{k}={v}")
    lines.append("")
    ENV_FILE.write_text("\n".join(lines))


# ---------------------------------------------------------------------------
# Wizard
# ---------------------------------------------------------------------------

def main() -> None:
    p()
    p("━" * 60)
    p("  Hermes Agent — Setup Wizard")
    p("━" * 60)

    env: dict[str, str] = {}

    # Load existing values as defaults
    existing: dict[str, str] = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()

    # ── Step 1: AI Provider ─────────────────────────────────────────────────
    p()
    p("STEP 1 — Choose your AI provider")
    p()
    p("  gemini     Google Gemini 2.0 Flash — FREE (1500 requests/day), recommended")
    p("  openrouter OpenRouter free models  — FREE, good variety")
    p("  anthropic  Claude by Anthropic     — PAID, best quality")
    p()
    provider = ask_choice("Provider", ["gemini", "openrouter", "anthropic"],
                          default=existing.get("HERMES_PROVIDER", "gemini"))
    env["HERMES_PROVIDER"] = provider

    # ── Step 2: AI API key ──────────────────────────────────────────────────
    p()
    if provider == "gemini":
        p("STEP 2 — Google Gemini API key")
        p()
        p("  1. Open: aistudio.google.com")
        p("  2. Click 'Get API key' → 'Create API key'")
        p("  3. Copy the key (starts with AIza...)")
        p()
        while True:
            key = ask("Paste your Gemini API key", secret=True,
                      default=existing.get("GEMINI_API_KEY", ""))
            if not key:
                p("  Key is required.")
                continue
            p("  Testing key... ", end="", flush=True)
            if test_gemini_key(key):
                p("✅ Valid!")
                env["GEMINI_API_KEY"] = key
                env["GEMINI_MODEL"] = existing.get("GEMINI_MODEL", "gemini-2.0-flash")
                break
            else:
                p("❌ Invalid or cannot reach Google. Double-check the key and try again.")

    elif provider == "openrouter":
        p("STEP 2 — OpenRouter API key")
        p()
        p("  1. Open: openrouter.ai → sign up (free)")
        p("  2. Go to Dashboard → Keys → Create Key")
        p("  3. Copy the key (starts with sk-or-...)")
        p()
        key = ask("Paste your OpenRouter API key", secret=True,
                  default=existing.get("OPENROUTER_API_KEY", ""))
        env["OPENROUTER_API_KEY"] = key
        env["OPENROUTER_MODEL"] = existing.get("OPENROUTER_MODEL",
                                               "meta-llama/llama-3.1-8b-instruct:free")

    elif provider == "anthropic":
        p("STEP 2 — Anthropic API key")
        p()
        p("  1. Open: console.anthropic.com")
        p("  2. Go to API Keys → Create Key")
        p("  3. Copy the key (starts with sk-ant-...)")
        p()
        key = ask("Paste your Anthropic API key", secret=True,
                  default=existing.get("ANTHROPIC_API_KEY", ""))
        env["ANTHROPIC_API_KEY"] = key
        env["HERMES_MODEL"] = existing.get("HERMES_MODEL", "claude-sonnet-4-6")

    # ── Step 3: Telegram bot token ──────────────────────────────────────────
    p()
    p("STEP 3 — Telegram bot token")
    p()
    p("  If you don't have a bot yet:")
    p("  1. Open Telegram → search @BotFather")
    p("  2. Send /newbot → follow the prompts")
    p("  3. Copy the token BotFather gives you")
    p()
    p("  If your old token was revoked:")
    p("  1. Message @BotFather → /revoke → select your bot")
    p("  2. Copy the NEW token")
    p()
    while True:
        token = ask("Paste your bot token", secret=True,
                    default=existing.get("TELEGRAM_BOT_TOKEN", ""))
        if not token:
            p("  Token is required.")
            continue
        p("  Testing token... ", end="", flush=True)
        username = test_telegram_token(token)
        if username:
            p(f"✅ Valid! Your bot is @{username}")
            env["TELEGRAM_BOT_TOKEN"] = token
            break
        else:
            p("❌ Invalid token. It may be revoked — go to @BotFather → /revoke to get a new one.")

    # ── Step 4: Telegram user ID ─────────────────────────────────────────────
    p()
    p("STEP 4 — Your Telegram user ID (locks the bot so only you can use it)")
    p()
    p("  1. Open Telegram → search @userinfobot")
    p("  2. Send any message — it replies with your 'Id:'")
    p("  3. Copy that number")
    p()
    uid = ask("Your Telegram user ID", default=existing.get("TELEGRAM_ALLOWED_USERS", ""))
    env["TELEGRAM_ALLOWED_USERS"] = uid

    # ── Step 5: Optional — voice transcription ──────────────────────────────
    p()
    p("STEP 5 — Voice memo transcription (optional)")
    p()
    p("  Enables automatic transcription of voice messages via OpenAI Whisper.")
    p("  Requires an OpenAI API key (has a small cost per minute of audio).")
    p()
    want_voice = ask_choice("Enable voice transcription?", ["yes", "no"], default="no")
    if want_voice == "yes":
        p()
        p("  1. Open: platform.openai.com → API keys → Create new secret key")
        p("  2. Copy the key (starts with sk-...)")
        p()
        oai_key = ask("Paste your OpenAI API key", secret=True,
                      default=existing.get("OPENAI_API_KEY", ""))
        env["OPENAI_API_KEY"] = oai_key
    elif existing.get("OPENAI_API_KEY"):
        env["OPENAI_API_KEY"] = existing["OPENAI_API_KEY"]

    # ── Write .env ───────────────────────────────────────────────────────────
    p()
    write_env(env)
    p(f"✅ Configuration saved to {ENV_FILE}")

    # ── Done ─────────────────────────────────────────────────────────────────
    p()
    p("━" * 60)
    p("  Setup complete! Start your bot with:")
    p()
    p("      python telegram_gateway.py")
    p()
    p("  Or run a health check first:")
    p()
    p("      python doctor.py")
    p("━" * 60)
    p()


if __name__ == "__main__":
    main()
